name: Build and Deploy DWS Stories

on:
  # Runs on pushes targeting the main branch
  push:
    branches: ["main"]
    paths:
      - 'expansions/DWSStories/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: Update-Stories
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Database Build Script
        # This navigates to the folder and runs the script before deploying
        run: |
          cd expansions/DWSStories
          node build.js

      - name: Setup Stories Database
        uses: actions/configure-pages@v4

      - name: Upload Database
        uses: actions/upload-pages-artifact@v3
        with:
          # Uploads the entire repository to be hosted on Pages
          path: '.'

      - name: Deploy!
        id: deployment
        uses: actions/deploy-pages@v4
